export const PADDING = 40
export const ROWS_COUNT = 5
export const WIDTH = 600
export const HEIGHT = 200
export const DPI_WIDTH = WIDTH * 2
export const DPI_HEIGHT = HEIGHT * 2
export const VIEW_HEIGHT = DPI_HEIGHT - PADDING * 2
export const VIEW_WIDTH = DPI_WIDTH
export const CIRCLE_RADIUS = 8
